### ISSUE TITLE
Add linting and prettier features

### ISSUE THREAD

**Issue by Mic-360** [Mic-360/link-short-hacktoberfest2022#4]
Convert eslintrc.json to eslintrc then define proper linting rules and define a pretty prettier rule.

**Comment by ahmedelbilal** [comment]
i would like to handle this

**Comment by Mic-360** [comment]
> i would like to handle this

Okay I'm assigning this to you.

**Comment by ahmedelbilal** [comment]
Check #5

**Comment by Mic-360** [comment]
Thanks for your work.
